apiVersion: v1
kind: ConfigMap
metadata:
  name: kubera-core-config
data:
  CONFIGMAP_NAME: kubera-core-config
  SECRET_NAME: kubera-oauth-credentials
  DB_SERVER: mongodb://{{ .Release.Name }}-mongodb:27017
  FRONTEND_URL: http://kubera-core-ui:9091
  AUTH_URL: http://localhost:3000/login
  DB_USER: root
  DB_PASSWORD: password
  PORTAL_URL: http://kubera-core-ui:9091
  LITMUS_SA: {{ .Release.Namespace }}-kubera-litmus-svc-account
  PROPEL_SA: {{ .Release.Namespace }}-kubera-propel-svc-account
  IMAGE_REG: {{ .Values.image.registry }}
  IMAGE_ORG: {{ .Values.image.organization }}
  IMAGE_TAG: {{ .Values.image.tag }}
  RELEASE_NAME: {{ .Release.Name }}
  {{- if .Values.domain }}
  DOMAIN_NAME: {{ .Values.domain }}
  {{- else }}
  DOMAIN_NAME: ""
  {{- end }}
  {{- if .Values.basepath }}
  BASE_PATH: {{ .Values.basepath }}
  {{- end }}
  {{- if .Values.chaospath }}
  CHAOS_PATH: {{ .Values.chaospath }}
  {{- end }}
  {{- if .Values.propelpath }}
  PROPEL_PATH: {{ .Values.propelpath }}
  {{- end }}
  SCHEME: {{ .Values.scheme }}
  {{- if .Values.imagePullSecret }}
  IMG_PULL_SECRET: {{ .Values.imagePullSecret }}
  {{- else }}
  IMG_PULL_SECRET: kubera-img-pull-secret
  {{- end }}
