apiVersion: v1
kind: ConfigMap
metadata:
  name: kubera-core-config
data:
  JWT_SECRET: cluster
  DB_SERVER: "mongodb://{{ .Release.Name }}-mongodb:27017"
  FRONTEND_URL: "http://google.com"
  AUTH_URL: "http://localhost:3000/login"
  DB_USER: "root"
  DB_PASSWORD: "password"
